class SeedSeeds < ActiveRecord::Migration[6.0]
  def change
    seeds1 = Seed.create title: 'Абрикос маньчжурский', latin_title: 'Armeniaca mandshurica'
    seeds2 = Seed.create title: 'Акантопанакс сидячецветковый', latin_title: 'Eleutherococcus sessiliflorus'
    seeds3 = Seed.create title: 'Актинидия Аргутта', latin_title: 'Actinidia arguta'
    seeds4 = Seed.create title: 'Барбарис амурский', latin_title: 'Berberis amurensis'
    seeds5 = Seed.create title: 'Бархат амурский', latin_title: 'Phellodendron amurense'
    seeds6 = Seed.create title: 'Берёза чёрная (даурская)', latin_title: 'Betula davurica'
    seeds7 = Seed.create title: 'Боярышник Арнольда', latin_title: 'Crataegus arnoldiana'
    seeds8 = Seed.create title: 'Боярышник кроваво-красный ', latin_title: 'Crataegus sanguinea'
    seeds9 = Seed.create title: 'Боярышник крупноколючковый', latin_title: 'Crataegus macracantha'
    seeds10 = Seed.create title: 'Боярышник перистонадрезаный', latin_title: 'Crataegus pinnatifida'
    seeds11 = Seed.create title: 'Виноград амурский', latin_title: 'Vitis amurensis'
    seeds12 = Seed.create title: 'Виноград девичий пятилисточковый', latin_title: 'Parthenocissus quinquefolia'
    seeds13 = Seed.create title: 'Груша уссурийская', latin_title: 'Pyrus ussuriensis'
    seeds14 = Seed.create title: 'Дуб монгольский', latin_title: 'Quercus mongolica'
    seeds15 = Seed.create title: 'Дуб черешчатый', latin_title: 'Quercus robur'
    seeds16 = Seed.create title: 'Калина Саржента', latin_title: 'Viburnum sargentii'
    seeds17 = Seed.create title: 'Катальпа яйцевидная', latin_title: 'Catalpa ovata'
    seeds18 = Seed.create title: 'Кедр корейский', latin_title: 'Pinus koraiensis'
    seeds19 = Seed.create title: 'Кедр сибирский', latin_title: 'Pinus sibirica'
    seeds20 = Seed.create title: 'Кизильник блестящий', latin_title: 'Cotoneaster lucidus'
    seeds21 = Seed.create title: 'Клён Гинала (приречный)', latin_title: 'Acer ginnala'
    seeds22 = Seed.create title: 'Клён зеленокорый', latin_title: 'Acer tegmentosum'
    seeds23 = Seed.create title: 'Клён ложнозибольдов', latin_title: 'Acer sieboldianum'
    seeds24 = Seed.create title: 'Клён маньчжурский', latin_title: 'Acer mandshuricum'
    seeds25 = Seed.create title: 'Клён мелколистный', latin_title: 'Acer mono'
    seeds26 = Seed.create title: 'Клён остролистный', latin_title: 'Acer platanoides'
    seeds27 = Seed.create title: 'Лимонник китайский', latin_title: 'Schisandra chinensis'
    seeds28 = Seed.create title: 'Липа сердцевидная', latin_title: 'Tilia cordata'
    seeds29 = Seed.create title: 'Магнолия Зибольда', latin_title: 'Magnolia sieboldii'
    seeds30 = Seed.create title: 'Магнолия Кобус', latin_title: 'Magnolia Kobus'
    seeds31 = Seed.create title: 'Магнолия Обратнояицевидная', latin_title: 'Magnolia obovata'
    seeds32 = Seed.create title: 'Орех маньчжурский', latin_title: 'Juglans mandshurica'
    seeds33 = Seed.create title: 'Рододендрон клейкий', latin_title: 'Rhododendron viscosum'
    seeds34 = Seed.create title: 'Рододендрон Шлипенбаха', latin_title: 'Rhododendron schlippenbachii'
    seeds35 = Seed.create title: 'Черемуха Виргинская', latin_title: 'Padus virginiana'
    seeds36 = Seed.create title: 'Черемуха Маака', latin_title: 'Padus maackii'
    seeds37 = Seed.create title: 'Шиповник морщинистый', latin_title: 'Rosa rugosa'
    seeds38 = Seed.create title: 'Элеутерококк колючий', latin_title: 'Eleutherococcus senticosus'
    seeds39 = Seed.create title: 'Яблоня ягодная', latin_title: 'Malus baccata'
  end
end